{
    'name': 'Project Management',
    'version': '1.0',
    'category': 'Project',
    'author': 'Your Name',
    'website': 'https://www.yourwebsite.com',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/project_views.xml',
        'views/task_views.xml',
        'views/task_wizard_views.xml',
        'reports/task_report_template.xml',
        'data/email_templates.xml',
        'data/demo_data.xml',
    ],
    'installable': True,
    'application': True,
}